# Generated by Django 4.1.4 on 2022-12-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
